H2rg dev
CaltechOpticalObservatories/camera-interface-v1 pull request #1
Opened 2024-05-29 21:26 UTC by scizen9

Added functions to implement H2RG windowing and low-latency image fetching from Archon.

Most updates are isolated in new functions.

Also made more compliant with clang-tidy recommendations for code structure.

2024-05-30 20:58 UTC, astronomerdave requested changes
see interspersed comments, and email

2024-05-30 20:58 UTC, astronomerdave commented on CMakeLists.txt
(from git manual):
_Note
This command has been superseded by alternatives:
    Use add_compile_definitions() to add preprocessor definitions.
    Use include_directories() to add include directories.
    Use add_compile_options() to add other options._

So I would suggest replacing this change with "**include_directories(/usr/local/include)**" but, what problem is this solving? I haven't run into the need for this before.

2024-05-30 20:58 UTC, astronomerdave commented on camerad/CMakeLists.txt
This change should not be here. Further down in the same file, generic.cpp is appended to the INTERFACE_SOURCE list when you define the instrument with -DINSTR=generic.  This change would cause a conflict if one were defining a non-generic instrument.

2024-05-30 20:58 UTC, astronomerdave commented on camerad/archon.cpp
> +  Interface::~Interface() = default;
This change is certainly better than what was there before, but I am now in favor of not even defining a de/constructor if it's going to be empty or defaulted, and have been making those changes.

2024-05-30 20:58 UTC, astronomerdave commented on camerad/archon.cpp
> +    this->win_vstop = 2047;
These look like pretty specialized values.

2024-05-30 20:58 UTC, astronomerdave commented on camerad/archon.cpp
> -   * The multiple-controller version will pass a reference to a return string. //TODO
The **//TODO** is an important tag, understood by Doxygen which makes a nice list of things I need to remember to come back to.

2024-05-30 20:58 UTC, astronomerdave commented on emulator/emulator-archon.cpp
I have made _extensive_ changes to the emulator but unfortunately (sorry) I didn't commit them yet. I need to commit those changes first.

This would be an _excellent_ area to get input though, because there are still some aspects that don't completely work still, including the artificial data. But let me commit my changes first.

2024-06-20 20:44 UTC, scizen9 commented
I'm closing this enormous PR in favor of more atomic PRs.  The notes above will be preserved in the closed PR.

2024-06-20 20:44 UTC, closed without merging